In [24]:
# importing libraries
import tensorflow_hub as hub
import tensorflow_text as text

In [25]:
# Links for preprocessing and bert encider model consist of 12 layers
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [26]:
# Using bert pre-processed model

bert_preprocess_model = hub.KerasLayer(preprocess_url)

2023-05-31 09:24:15.876416: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'seq_length' with dtype int32
	 [[{{node seq_length}}]]
2023-05-31 09:24:15.877267: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'seq_length' with dtype int32
	 [[{{node seq_length}}]]
2023-05-31 09:24:15.877436: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'seq_length' with dtype int32
	 [[{{node seq_length}}]]
2023-05-31 09:24:15.878053: I tensorflow/core/

In [27]:
# making dummy text to check model accuracy and results

test_text = ['I love Python Programming', 'I loved to play complex python programming', 'It was a nice movie indeed']

text_preprocessed = bert_preprocess_model(test_text)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [28]:
text_preprocessed['input_word_ids']



<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[  101,  1045,  2293, 18750,  4730,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [29]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [30]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [31]:
bert_model = hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'encoder_outputs', 'default', 'sequence_output'])

In [33]:
# array is consist of embedding vector shape consist of sample data size means how many sentences are input and 
# second parameter is for embedding vector size
bert_results['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.917123  , -0.47935185, -0.7865698 , ..., -0.61751753,
        -0.71026856,  0.92184293],
       [-0.86224216, -0.55005187, -0.82012916, ..., -0.81606275,
        -0.7290942 ,  0.9089511 ],
       [-0.8356016 , -0.2345947 ,  0.14823484, ..., -0.03222021,
        -0.5324523 ,  0.86087686]], dtype=float32)>

In [34]:
bert_results['sequence_output'] # 0 0 0 0 0 0 <---- 128 refers to padding

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[-7.90061355e-02,  3.63351077e-01, -2.11015567e-01, ...,
         -1.71837658e-01,  1.62997246e-01,  6.72426701e-01],
        [ 2.78835416e-01,  4.37162936e-01, -3.57647479e-01, ...,
         -4.46368307e-02,  3.83151978e-01,  5.88798463e-01],
        [ 1.20376778e+00,  1.07270265e+00,  4.84087706e-01, ...,
          2.49209672e-01,  4.07308996e-01,  4.04818386e-01],
        ...,
        [ 8.63000378e-02,  1.93538383e-01,  4.75399971e-01, ...,
          1.88801542e-01, -6.47412390e-02,  3.13186258e-01],
        [ 1.58870488e-01,  2.85726607e-01,  3.73407662e-01, ...,
          9.30909142e-02, -4.96959612e-02,  3.87611330e-01],
        [-8.07989538e-02, -9.57285762e-02,  2.68097967e-01, ...,
          1.39795959e-01, -6.31583482e-02,  2.72883475e-01]],

       [[-8.93637240e-02,  1.79800346e-01, -2.82817990e-01, ...,
         -6.09668791e-02,  3.29918057e-01,  6.20530188e-01],
        [ 5.40217638e-01, -1.02205873e-01, -2.04

In [35]:
len(bert_results['encoder_outputs']) # means 12 layer network

12

In [36]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[ 0.18903583,  0.02752544, -0.06513746, ..., -0.00620215,
          0.15053889,  0.0316544 ],
        [ 0.5916147 ,  0.75891376, -0.07240672, ...,  0.6190398 ,
          0.8292889 ,  0.16161968],
        [ 1.4460827 ,  0.44602665,  0.40990278, ...,  0.48255903,
          0.62691146,  0.13463406],
        ...,
        [ 0.15147889, -0.21573836,  0.7032908 , ..., -0.1253722 ,
         -0.13787237,  0.27722055],
        [ 0.05143782, -0.24052714,  0.53569144, ..., -0.07915039,
         -0.03307901,  0.17380929],
        [ 0.20934701, -0.15645269,  0.60395426, ...,  0.3290353 ,
         -0.35827202,  0.08100387]],

       [[ 0.15421957, -0.00764418, -0.05819117, ..., -0.0169264 ,
          0.10595861,  0.03351918],
        [ 0.4643292 ,  0.8625841 , -0.12245551, ...,  0.4390656 ,
          1.0743841 ,  0.05581968],
        [ 0.88278234,  0.14644957,  0.938782  , ..., -0.6667722 ,
          0.24359389, -0.09170397],
        ...,