In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]]) 

In [3]:
profit = revenue - expenses
profit 

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
#Broadcasting numpy
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])


In [8]:
#ans = price_per_unit * units
ans = np.dot(price_per_unit, units)
ans

array([34400, 50000, 64400])

In [9]:
# Exercise
company_revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr = 75
ans2 = np.dot(company_revenue, inr)
ans2


array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [11]:
per_unit_price = np.array([[20,30,15]])
units_sold= np.array([[50,60,25],[10,13,5],[40,70,52]])

ans3 = np.dot(per_unit_price,units_sold)
ans3

array([[1900, 2640, 1430]])